version: '3.3'
services:
  tailscaled:
    hostname: ts-1
    container_name: tailscaled
    volumes:
      - '/tailscale-data:/var/lib'
      - '/lib/modules:/lib/modules'
      - './connect.sh:/connect.sh'
    cap_add:
      - net_admin
      - sys_module
    privileged: true
    image: tailscale/tailscale
    command: ash connect.sh